FROM java:8
#FROM openjdk:8-jdk
ENV SPRING_ACTIVE_PROFILE stage
ADD target/cloud-movie-demo-0.0.1-SNAPSHOT.war app.war
#ADD jennifer/agent.java agent.java
VOLUME /tmp
VOLUME /target
#RUN apt-get update && \
#    apt-get install -y net-tools
RUN bash -c 'touch /app.war'
CMD echo 'test'
#EXPOSE 8081
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=${SPRING_ACTIVE_PROFILE}", "-jar","/app.war"]